@baseUrl = http://localhost:3000/api/contacts

### Get all contacts
GET {{baseUrl}}
Content-Type: application/json


### Get contact by ID
GET {{baseUrl}}/1
Content-Type: application/json

Create a new 

### Update a contact
PUT {{baseUrl}}/1
Content-Type: application/json

{
    "name": "Jane Updated",
    "email": "jane.updated@xample.com
}

### Delete a contact
DELETE {{baseUrl}}/1
Content-Type: application/json